# http://docs.gitlab.com/ce/ci/yaml/README.html

image: node:12

workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null'

empty:
  script:
    - echo "test"

jira-build-integration-on-success:
  stage: .post
  when: on_success
  image: registry.gitlab.com/rohit-gohri/jira-ci-cd-integration:v0
  script: jira-integration
  variables:
    JIRA_ISSUES: JCI-7
    BUILD_STATE: successful
    BUILD_NAME: gitlab-pipeline
    JIRA_INSTANCE: boringdownload

jira-build-integration-on-failure:
  extends: jira-build-integration-on-success
  when: on_failure
  variables:
    BUILD_STATE: failure

jira-deploy-integration-on-success:
  extends: jira-build-integration-on-success
  variables:
    JIRA_ISSUES: JCI-4
  environment:
    name: production

jira-deploy-integration-on-failure:
  extends: jira-build-integration-on-failure
  variables:
    JIRA_ISSUES: JCI-4
  environment:
    name: production
