# http://docs.gitlab.com/ce/ci/yaml/README.html

image: node:12

workflow:
  rules:
    - if: $CI_COMMIT_TAG

jira-integration-on-success:
  stage: .post
  when: on_success
  image: registry.gitlab.com/rohit-gohri/jira-ci-cd-integration:v0
  script: jira-integration
  variables:
    BUILD_STATE: successful
    JIRA_ISSUES: JCI-7
    BUILD_NAME: gitlab-pipeline
    JIRA_INSTANCE: boringdownload

jira-integration-on-failure:
  extends: jira-integration-on-success
  when: on_failure
  variables:
    BUILD_STATE: failure
