name: 'build-test'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

env:
  YARN_COMPRESSION_LEVEL: 0
  YARN_ENABLE_GLOBAL_CACHE: true

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: Checks
        run: |
          yarn lint
          yarn build
          yarn test

      - name: 🔨 Package Action
        run: yarn package:action

      - name: Test Action - Build
        uses: ./
        if: ${{ always() }}
        env:
          JIRA_DEFAULT_TEST_ISSUE: 'JCI-7'
        with:
          state: ${{ job.status }}
          jira_instance: boringdownload
          token: ${{ secrets.GITHUB_TOKEN }}
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}

      - name: Test Action - Deploys
        uses: ./
        if: ${{ always() }}
        env:
          JIRA_DEFAULT_TEST_ISSUE: 'JCI-4'
        with:
          state: ${{ job.status }}
          environment: development
          jira_instance: boringdownload
          token: ${{ secrets.GITHUB_TOKEN }}
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
