name: 'test-release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Development Integration
        uses: rohit-gohri/jira-ci-cd-integration@v0
        if: ${{ always() }}
        env:
          JIRA_DEFAULT_TEST_ISSUE: 'JCI-7'
        with:
          state: ${{ job.status }}
          jira_instance: boringdownload
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}

  test-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Development Integration
        uses: rohit-gohri/jira-ci-cd-integration@v0
        if: ${{ always() }}
        env:
          JIRA_DEFAULT_TEST_ISSUE: 'JCI-4'
        with:
          state: ${{ job.status }}
          environment: production
          jira_instance: boringdownload
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
