name: 'release-test'

on:
  push:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Development Integration
        uses: rohit-gohri/jira-ci-cd-integration@v0
        env:
          JIRA_DEFAULT_TEST_ISSUE: 'JCI-7'
        with:
          event_type: build
          state: ${{ job.status }}
          jira_instance: boringdownload
          token: ${{ secrets.GITHUB_TOKEN }}
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}

  # TODO: Fix this
  # deployment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Jira Development Integration
  #       uses: rohit-gohri/jira-ci-cd-integration@v0
  #       env:
  #         JIRA_DEFAULT_TEST_ISSUE: 'JCI-7'
  #       with:
  #         event_type: deployment
  #         state: ${{ job.status }}
  #         jira_instance: boringdownload
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         client_id: ${{ secrets.JIRA_CLIENT_ID }}
  #         client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
